/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardDashboardStudioRouteImport } from './routes/(dashboard)/dashboard/studio'
import { Route as dashboardDashboardSettingsRouteImport } from './routes/(dashboard)/dashboard/settings'
import { Route as dashboardDashboardQuizzesRouteImport } from './routes/(dashboard)/dashboard/quizzes'
import { Route as dashboardDashboardCommunityRouteImport } from './routes/(dashboard)/dashboard/community'
import { Route as dashboardDashboardAssignmentsRouteImport } from './routes/(dashboard)/dashboard/assignments'
import { Route as dashboardDashboardAnalyticsRouteImport } from './routes/(dashboard)/dashboard/analytics'
import { Route as dashboardDashboardStudentsIndexRouteImport } from './routes/(dashboard)/dashboard/students/index'
import { Route as dashboardDashboardClassesIndexRouteImport } from './routes/(dashboard)/dashboard/classes/index'
import { Route as dashboardDashboardStudioCreateRouteImport } from './routes/(dashboard)/dashboard/studio_.create'
import { Route as dashboardDashboardStudioContentIdRouteImport } from './routes/(dashboard)/dashboard/studio_.$contentId'
import { Route as dashboardDashboardStudentsCreateRouteImport } from './routes/(dashboard)/dashboard/students/create'
import { Route as dashboardDashboardStudentsStudentIdRouteImport } from './routes/(dashboard)/dashboard/students/$studentId'
import { Route as dashboardDashboardQuizzesCreateRouteImport } from './routes/(dashboard)/dashboard/quizzes_.create'
import { Route as dashboardDashboardQuizzesQuizIdRouteImport } from './routes/(dashboard)/dashboard/quizzes_.$quizId'
import { Route as dashboardDashboardCommunitySubscriptionEditRouteImport } from './routes/(dashboard)/dashboard/community_.subscription-edit'
import { Route as dashboardDashboardCommunitySubscriptionCreateRouteImport } from './routes/(dashboard)/dashboard/community_.subscription-create'
import { Route as dashboardDashboardClassesCreateRouteImport } from './routes/(dashboard)/dashboard/classes/create'
import { Route as dashboardDashboardClassesClassIdRouteImport } from './routes/(dashboard)/dashboard/classes/$classId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRoute,
} as any)
const dashboardDashboardStudioRoute =
  dashboardDashboardStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardSettingsRoute =
  dashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardQuizzesRoute =
  dashboardDashboardQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunityRoute =
  dashboardDashboardCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAssignmentsRoute =
  dashboardDashboardAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAnalyticsRoute =
  dashboardDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudentsIndexRoute =
  dashboardDashboardStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardClassesIndexRoute =
  dashboardDashboardClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudioCreateRoute =
  dashboardDashboardStudioCreateRouteImport.update({
    id: '/studio_/create',
    path: '/studio/create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudioContentIdRoute =
  dashboardDashboardStudioContentIdRouteImport.update({
    id: '/studio_/$contentId',
    path: '/studio/$contentId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudentsCreateRoute =
  dashboardDashboardStudentsCreateRouteImport.update({
    id: '/students/create',
    path: '/students/create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudentsStudentIdRoute =
  dashboardDashboardStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardQuizzesCreateRoute =
  dashboardDashboardQuizzesCreateRouteImport.update({
    id: '/quizzes_/create',
    path: '/quizzes/create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardQuizzesQuizIdRoute =
  dashboardDashboardQuizzesQuizIdRouteImport.update({
    id: '/quizzes_/$quizId',
    path: '/quizzes/$quizId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunitySubscriptionEditRoute =
  dashboardDashboardCommunitySubscriptionEditRouteImport.update({
    id: '/community_/subscription-edit',
    path: '/community/subscription-edit',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunitySubscriptionCreateRoute =
  dashboardDashboardCommunitySubscriptionCreateRouteImport.update({
    id: '/community_/subscription-create',
    path: '/community/subscription-create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardClassesCreateRoute =
  dashboardDashboardClassesCreateRouteImport.update({
    id: '/classes/create',
    path: '/classes/create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardClassesClassIdRoute =
  dashboardDashboardClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/assignments': typeof dashboardDashboardAssignmentsRoute
  '/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/dashboard/quizzes': typeof dashboardDashboardQuizzesRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/dashboard/classes/$classId': typeof dashboardDashboardClassesClassIdRoute
  '/dashboard/classes/create': typeof dashboardDashboardClassesCreateRoute
  '/dashboard/community/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/dashboard/community/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/dashboard/quizzes/$quizId': typeof dashboardDashboardQuizzesQuizIdRoute
  '/dashboard/quizzes/create': typeof dashboardDashboardQuizzesCreateRoute
  '/dashboard/students/$studentId': typeof dashboardDashboardStudentsStudentIdRoute
  '/dashboard/students/create': typeof dashboardDashboardStudentsCreateRoute
  '/dashboard/studio/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/dashboard/studio/create': typeof dashboardDashboardStudioCreateRoute
  '/dashboard/classes/': typeof dashboardDashboardClassesIndexRoute
  '/dashboard/students/': typeof dashboardDashboardStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/assignments': typeof dashboardDashboardAssignmentsRoute
  '/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/dashboard/quizzes': typeof dashboardDashboardQuizzesRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/dashboard/classes/$classId': typeof dashboardDashboardClassesClassIdRoute
  '/dashboard/classes/create': typeof dashboardDashboardClassesCreateRoute
  '/dashboard/community/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/dashboard/community/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/dashboard/quizzes/$quizId': typeof dashboardDashboardQuizzesQuizIdRoute
  '/dashboard/quizzes/create': typeof dashboardDashboardQuizzesCreateRoute
  '/dashboard/students/$studentId': typeof dashboardDashboardStudentsStudentIdRoute
  '/dashboard/students/create': typeof dashboardDashboardStudentsCreateRoute
  '/dashboard/studio/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/dashboard/studio/create': typeof dashboardDashboardStudioCreateRoute
  '/dashboard/classes': typeof dashboardDashboardClassesIndexRoute
  '/dashboard/students': typeof dashboardDashboardStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(dashboard)/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/(dashboard)/dashboard/assignments': typeof dashboardDashboardAssignmentsRoute
  '/(dashboard)/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/(dashboard)/dashboard/quizzes': typeof dashboardDashboardQuizzesRoute
  '/(dashboard)/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/(dashboard)/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(dashboard)/dashboard/classes/$classId': typeof dashboardDashboardClassesClassIdRoute
  '/(dashboard)/dashboard/classes/create': typeof dashboardDashboardClassesCreateRoute
  '/(dashboard)/dashboard/community_/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/(dashboard)/dashboard/community_/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/(dashboard)/dashboard/quizzes_/$quizId': typeof dashboardDashboardQuizzesQuizIdRoute
  '/(dashboard)/dashboard/quizzes_/create': typeof dashboardDashboardQuizzesCreateRoute
  '/(dashboard)/dashboard/students/$studentId': typeof dashboardDashboardStudentsStudentIdRoute
  '/(dashboard)/dashboard/students/create': typeof dashboardDashboardStudentsCreateRoute
  '/(dashboard)/dashboard/studio_/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/(dashboard)/dashboard/studio_/create': typeof dashboardDashboardStudioCreateRoute
  '/(dashboard)/dashboard/classes/': typeof dashboardDashboardClassesIndexRoute
  '/(dashboard)/dashboard/students/': typeof dashboardDashboardStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/community'
    | '/dashboard/quizzes'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard/'
    | '/dashboard/classes/$classId'
    | '/dashboard/classes/create'
    | '/dashboard/community/subscription-create'
    | '/dashboard/community/subscription-edit'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/quizzes/create'
    | '/dashboard/students/$studentId'
    | '/dashboard/students/create'
    | '/dashboard/studio/$contentId'
    | '/dashboard/studio/create'
    | '/dashboard/classes/'
    | '/dashboard/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/analytics'
    | '/dashboard/assignments'
    | '/dashboard/community'
    | '/dashboard/quizzes'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard'
    | '/dashboard/classes/$classId'
    | '/dashboard/classes/create'
    | '/dashboard/community/subscription-create'
    | '/dashboard/community/subscription-edit'
    | '/dashboard/quizzes/$quizId'
    | '/dashboard/quizzes/create'
    | '/dashboard/students/$studentId'
    | '/dashboard/students/create'
    | '/dashboard/studio/$contentId'
    | '/dashboard/studio/create'
    | '/dashboard/classes'
    | '/dashboard/students'
  id:
    | '__root__'
    | '/'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/dashboard/analytics'
    | '/(dashboard)/dashboard/assignments'
    | '/(dashboard)/dashboard/community'
    | '/(dashboard)/dashboard/quizzes'
    | '/(dashboard)/dashboard/settings'
    | '/(dashboard)/dashboard/studio'
    | '/(dashboard)/dashboard/'
    | '/(dashboard)/dashboard/classes/$classId'
    | '/(dashboard)/dashboard/classes/create'
    | '/(dashboard)/dashboard/community_/subscription-create'
    | '/(dashboard)/dashboard/community_/subscription-edit'
    | '/(dashboard)/dashboard/quizzes_/$quizId'
    | '/(dashboard)/dashboard/quizzes_/create'
    | '/(dashboard)/dashboard/students/$studentId'
    | '/(dashboard)/dashboard/students/create'
    | '/(dashboard)/dashboard/studio_/$contentId'
    | '/(dashboard)/dashboard/studio_/create'
    | '/(dashboard)/dashboard/classes/'
    | '/(dashboard)/dashboard/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio': {
      id: '/(dashboard)/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof dashboardDashboardStudioRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/settings': {
      id: '/(dashboard)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/quizzes': {
      id: '/(dashboard)/dashboard/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/quizzes'
      preLoaderRoute: typeof dashboardDashboardQuizzesRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community': {
      id: '/(dashboard)/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof dashboardDashboardCommunityRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/assignments': {
      id: '/(dashboard)/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof dashboardDashboardAssignmentsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/analytics': {
      id: '/(dashboard)/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof dashboardDashboardAnalyticsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/students/': {
      id: '/(dashboard)/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof dashboardDashboardStudentsIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/classes/': {
      id: '/(dashboard)/dashboard/classes/'
      path: '/classes'
      fullPath: '/dashboard/classes/'
      preLoaderRoute: typeof dashboardDashboardClassesIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio_/create': {
      id: '/(dashboard)/dashboard/studio_/create'
      path: '/studio/create'
      fullPath: '/dashboard/studio/create'
      preLoaderRoute: typeof dashboardDashboardStudioCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio_/$contentId': {
      id: '/(dashboard)/dashboard/studio_/$contentId'
      path: '/studio/$contentId'
      fullPath: '/dashboard/studio/$contentId'
      preLoaderRoute: typeof dashboardDashboardStudioContentIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/students/create': {
      id: '/(dashboard)/dashboard/students/create'
      path: '/students/create'
      fullPath: '/dashboard/students/create'
      preLoaderRoute: typeof dashboardDashboardStudentsCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/students/$studentId': {
      id: '/(dashboard)/dashboard/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/dashboard/students/$studentId'
      preLoaderRoute: typeof dashboardDashboardStudentsStudentIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/quizzes_/create': {
      id: '/(dashboard)/dashboard/quizzes_/create'
      path: '/quizzes/create'
      fullPath: '/dashboard/quizzes/create'
      preLoaderRoute: typeof dashboardDashboardQuizzesCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/quizzes_/$quizId': {
      id: '/(dashboard)/dashboard/quizzes_/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/dashboard/quizzes/$quizId'
      preLoaderRoute: typeof dashboardDashboardQuizzesQuizIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community_/subscription-edit': {
      id: '/(dashboard)/dashboard/community_/subscription-edit'
      path: '/community/subscription-edit'
      fullPath: '/dashboard/community/subscription-edit'
      preLoaderRoute: typeof dashboardDashboardCommunitySubscriptionEditRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community_/subscription-create': {
      id: '/(dashboard)/dashboard/community_/subscription-create'
      path: '/community/subscription-create'
      fullPath: '/dashboard/community/subscription-create'
      preLoaderRoute: typeof dashboardDashboardCommunitySubscriptionCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/classes/create': {
      id: '/(dashboard)/dashboard/classes/create'
      path: '/classes/create'
      fullPath: '/dashboard/classes/create'
      preLoaderRoute: typeof dashboardDashboardClassesCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/classes/$classId': {
      id: '/(dashboard)/dashboard/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/dashboard/classes/$classId'
      preLoaderRoute: typeof dashboardDashboardClassesClassIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
  }
}

interface dashboardDashboardRouteChildren {
  dashboardDashboardAnalyticsRoute: typeof dashboardDashboardAnalyticsRoute
  dashboardDashboardAssignmentsRoute: typeof dashboardDashboardAssignmentsRoute
  dashboardDashboardCommunityRoute: typeof dashboardDashboardCommunityRoute
  dashboardDashboardQuizzesRoute: typeof dashboardDashboardQuizzesRoute
  dashboardDashboardSettingsRoute: typeof dashboardDashboardSettingsRoute
  dashboardDashboardStudioRoute: typeof dashboardDashboardStudioRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardDashboardClassesClassIdRoute: typeof dashboardDashboardClassesClassIdRoute
  dashboardDashboardClassesCreateRoute: typeof dashboardDashboardClassesCreateRoute
  dashboardDashboardCommunitySubscriptionCreateRoute: typeof dashboardDashboardCommunitySubscriptionCreateRoute
  dashboardDashboardCommunitySubscriptionEditRoute: typeof dashboardDashboardCommunitySubscriptionEditRoute
  dashboardDashboardQuizzesQuizIdRoute: typeof dashboardDashboardQuizzesQuizIdRoute
  dashboardDashboardQuizzesCreateRoute: typeof dashboardDashboardQuizzesCreateRoute
  dashboardDashboardStudentsStudentIdRoute: typeof dashboardDashboardStudentsStudentIdRoute
  dashboardDashboardStudentsCreateRoute: typeof dashboardDashboardStudentsCreateRoute
  dashboardDashboardStudioContentIdRoute: typeof dashboardDashboardStudioContentIdRoute
  dashboardDashboardStudioCreateRoute: typeof dashboardDashboardStudioCreateRoute
  dashboardDashboardClassesIndexRoute: typeof dashboardDashboardClassesIndexRoute
  dashboardDashboardStudentsIndexRoute: typeof dashboardDashboardStudentsIndexRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardAnalyticsRoute: dashboardDashboardAnalyticsRoute,
  dashboardDashboardAssignmentsRoute: dashboardDashboardAssignmentsRoute,
  dashboardDashboardCommunityRoute: dashboardDashboardCommunityRoute,
  dashboardDashboardQuizzesRoute: dashboardDashboardQuizzesRoute,
  dashboardDashboardSettingsRoute: dashboardDashboardSettingsRoute,
  dashboardDashboardStudioRoute: dashboardDashboardStudioRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  dashboardDashboardClassesClassIdRoute: dashboardDashboardClassesClassIdRoute,
  dashboardDashboardClassesCreateRoute: dashboardDashboardClassesCreateRoute,
  dashboardDashboardCommunitySubscriptionCreateRoute:
    dashboardDashboardCommunitySubscriptionCreateRoute,
  dashboardDashboardCommunitySubscriptionEditRoute:
    dashboardDashboardCommunitySubscriptionEditRoute,
  dashboardDashboardQuizzesQuizIdRoute: dashboardDashboardQuizzesQuizIdRoute,
  dashboardDashboardQuizzesCreateRoute: dashboardDashboardQuizzesCreateRoute,
  dashboardDashboardStudentsStudentIdRoute:
    dashboardDashboardStudentsStudentIdRoute,
  dashboardDashboardStudentsCreateRoute: dashboardDashboardStudentsCreateRoute,
  dashboardDashboardStudioContentIdRoute:
    dashboardDashboardStudioContentIdRoute,
  dashboardDashboardStudioCreateRoute: dashboardDashboardStudioCreateRoute,
  dashboardDashboardClassesIndexRoute: dashboardDashboardClassesIndexRoute,
  dashboardDashboardStudentsIndexRoute: dashboardDashboardStudentsIndexRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
