/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as dashboardDashboardIndexRouteImport } from './routes/(dashboard)/dashboard/index'
import { Route as dashboardDashboardStudioRouteImport } from './routes/(dashboard)/dashboard/studio'
import { Route as dashboardDashboardSettingsRouteImport } from './routes/(dashboard)/dashboard/settings'
import { Route as dashboardDashboardCommunityRouteImport } from './routes/(dashboard)/dashboard/community'
import { Route as dashboardDashboardAnalyticsRouteImport } from './routes/(dashboard)/dashboard/analytics'
import { Route as dashboardDashboardStudioCreateRouteImport } from './routes/(dashboard)/dashboard/studio_.create'
import { Route as dashboardDashboardStudioContentIdRouteImport } from './routes/(dashboard)/dashboard/studio_.$contentId'
import { Route as dashboardDashboardCommunitySubscriptionEditRouteImport } from './routes/(dashboard)/dashboard/community_.subscription-edit'
import { Route as dashboardDashboardCommunitySubscriptionCreateRouteImport } from './routes/(dashboard)/dashboard/community_.subscription-create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardIndexRoute = dashboardDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardDashboardRoute,
} as any)
const dashboardDashboardStudioRoute =
  dashboardDashboardStudioRouteImport.update({
    id: '/studio',
    path: '/studio',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardSettingsRoute =
  dashboardDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunityRoute =
  dashboardDashboardCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardAnalyticsRoute =
  dashboardDashboardAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudioCreateRoute =
  dashboardDashboardStudioCreateRouteImport.update({
    id: '/studio_/create',
    path: '/studio/create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardStudioContentIdRoute =
  dashboardDashboardStudioContentIdRouteImport.update({
    id: '/studio_/$contentId',
    path: '/studio/$contentId',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunitySubscriptionEditRoute =
  dashboardDashboardCommunitySubscriptionEditRouteImport.update({
    id: '/community_/subscription-edit',
    path: '/community/subscription-edit',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
const dashboardDashboardCommunitySubscriptionCreateRoute =
  dashboardDashboardCommunitySubscriptionCreateRouteImport.update({
    id: '/community_/subscription-create',
    path: '/community/subscription-create',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof dashboardDashboardRouteWithChildren
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/dashboard/': typeof dashboardDashboardIndexRoute
  '/dashboard/community/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/dashboard/community/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/dashboard/studio/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/dashboard/studio/create': typeof dashboardDashboardStudioCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/dashboard': typeof dashboardDashboardIndexRoute
  '/dashboard/community/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/dashboard/community/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/dashboard/studio/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/dashboard/studio/create': typeof dashboardDashboardStudioCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRouteWithChildren
  '/(dashboard)/dashboard/analytics': typeof dashboardDashboardAnalyticsRoute
  '/(dashboard)/dashboard/community': typeof dashboardDashboardCommunityRoute
  '/(dashboard)/dashboard/settings': typeof dashboardDashboardSettingsRoute
  '/(dashboard)/dashboard/studio': typeof dashboardDashboardStudioRoute
  '/(dashboard)/dashboard/': typeof dashboardDashboardIndexRoute
  '/(dashboard)/dashboard/community_/subscription-create': typeof dashboardDashboardCommunitySubscriptionCreateRoute
  '/(dashboard)/dashboard/community_/subscription-edit': typeof dashboardDashboardCommunitySubscriptionEditRoute
  '/(dashboard)/dashboard/studio_/$contentId': typeof dashboardDashboardStudioContentIdRoute
  '/(dashboard)/dashboard/studio_/create': typeof dashboardDashboardStudioCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard/'
    | '/dashboard/community/subscription-create'
    | '/dashboard/community/subscription-edit'
    | '/dashboard/studio/$contentId'
    | '/dashboard/studio/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/analytics'
    | '/dashboard/community'
    | '/dashboard/settings'
    | '/dashboard/studio'
    | '/dashboard'
    | '/dashboard/community/subscription-create'
    | '/dashboard/community/subscription-edit'
    | '/dashboard/studio/$contentId'
    | '/dashboard/studio/create'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(dashboard)/dashboard'
    | '/(dashboard)/dashboard/analytics'
    | '/(dashboard)/dashboard/community'
    | '/(dashboard)/dashboard/settings'
    | '/(dashboard)/dashboard/studio'
    | '/(dashboard)/dashboard/'
    | '/(dashboard)/dashboard/community_/subscription-create'
    | '/(dashboard)/dashboard/community_/subscription-edit'
    | '/(dashboard)/dashboard/studio_/$contentId'
    | '/(dashboard)/dashboard/studio_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard/': {
      id: '/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof dashboardDashboardIndexRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio': {
      id: '/(dashboard)/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof dashboardDashboardStudioRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/settings': {
      id: '/(dashboard)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community': {
      id: '/(dashboard)/dashboard/community'
      path: '/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof dashboardDashboardCommunityRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/analytics': {
      id: '/(dashboard)/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof dashboardDashboardAnalyticsRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio_/create': {
      id: '/(dashboard)/dashboard/studio_/create'
      path: '/studio/create'
      fullPath: '/dashboard/studio/create'
      preLoaderRoute: typeof dashboardDashboardStudioCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/studio_/$contentId': {
      id: '/(dashboard)/dashboard/studio_/$contentId'
      path: '/studio/$contentId'
      fullPath: '/dashboard/studio/$contentId'
      preLoaderRoute: typeof dashboardDashboardStudioContentIdRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community_/subscription-edit': {
      id: '/(dashboard)/dashboard/community_/subscription-edit'
      path: '/community/subscription-edit'
      fullPath: '/dashboard/community/subscription-edit'
      preLoaderRoute: typeof dashboardDashboardCommunitySubscriptionEditRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
    '/(dashboard)/dashboard/community_/subscription-create': {
      id: '/(dashboard)/dashboard/community_/subscription-create'
      path: '/community/subscription-create'
      fullPath: '/dashboard/community/subscription-create'
      preLoaderRoute: typeof dashboardDashboardCommunitySubscriptionCreateRouteImport
      parentRoute: typeof dashboardDashboardRoute
    }
  }
}

interface dashboardDashboardRouteChildren {
  dashboardDashboardAnalyticsRoute: typeof dashboardDashboardAnalyticsRoute
  dashboardDashboardCommunityRoute: typeof dashboardDashboardCommunityRoute
  dashboardDashboardSettingsRoute: typeof dashboardDashboardSettingsRoute
  dashboardDashboardStudioRoute: typeof dashboardDashboardStudioRoute
  dashboardDashboardIndexRoute: typeof dashboardDashboardIndexRoute
  dashboardDashboardCommunitySubscriptionCreateRoute: typeof dashboardDashboardCommunitySubscriptionCreateRoute
  dashboardDashboardCommunitySubscriptionEditRoute: typeof dashboardDashboardCommunitySubscriptionEditRoute
  dashboardDashboardStudioContentIdRoute: typeof dashboardDashboardStudioContentIdRoute
  dashboardDashboardStudioCreateRoute: typeof dashboardDashboardStudioCreateRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardAnalyticsRoute: dashboardDashboardAnalyticsRoute,
  dashboardDashboardCommunityRoute: dashboardDashboardCommunityRoute,
  dashboardDashboardSettingsRoute: dashboardDashboardSettingsRoute,
  dashboardDashboardStudioRoute: dashboardDashboardStudioRoute,
  dashboardDashboardIndexRoute: dashboardDashboardIndexRoute,
  dashboardDashboardCommunitySubscriptionCreateRoute:
    dashboardDashboardCommunitySubscriptionCreateRoute,
  dashboardDashboardCommunitySubscriptionEditRoute:
    dashboardDashboardCommunitySubscriptionEditRoute,
  dashboardDashboardStudioContentIdRoute:
    dashboardDashboardStudioContentIdRoute,
  dashboardDashboardStudioCreateRoute: dashboardDashboardStudioCreateRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
